SIMULATION_N_SIMS_MIN = 1_000
SIMULATION_N_SIMS_MAX = 200_000
SIMULATION_TARGET_WEEKS_MIN = 1
SIMULATION_HORIZON_WEEKS_MAX = 521
SIMULATION_THROUGHPUT_SAMPLES_MIN = 6
SIMULATION_THROUGHPUT_SAMPLES_MAX = 521
SIMULATION_BACKLOG_SIZE_MIN = 1
SIMULATION_BACKLOG_SIZE_MAX = 1_000_000
